//! Hardcoded unit data for the eco guide
//! These units are embedded in the frontend for GitHub Pages deployment

use super::unit::{Faction, Unit};
use std::collections::HashMap;

/// Get the base engineer unit ID for each faction
pub fn faction_engineer_id(faction: Faction) -> &'static str {
    match faction {
        Faction::Uef => "UEL0105",
        Faction::Cybran => "URL0105",
        Faction::Aeon => "UAL0105",
        Faction::Seraphim => "XSL0105",
    }
}

/// Get all units as a vector
pub fn all_units() -> Vec<Unit> {
    let mut units = Vec::new();
    units.extend(uef_units());
    units.extend(cybran_units());
    units.extend(aeon_units());
    units.extend(seraphim_units());
    units
}

/// Get units grouped by faction
pub fn units_by_faction() -> HashMap<Faction, Vec<Unit>> {
    let mut map = HashMap::new();
    for faction in Faction::all() {
        let units: Vec<Unit> = all_units()
            .into_iter()
            .filter(|u| u.faction == faction)
            .collect();
        map.insert(faction, units);
    }
    map
}

/// Find a unit by its unit_id
pub fn find_unit(unit_id: &str) -> Option<Unit> {
    all_units().into_iter().find(|u| u.unit_id == unit_id)
}

/// UEF units
pub fn uef_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "UEL0105".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH1".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UEL0208".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH2".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UEL0301".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2100,
            build_cost_energy: 25200,
            build_time: 14400,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH3".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UEL0309".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 312,
            build_cost_energy: 1560,
            build_time: 1560,
            categories: vec![
                "ENGINEER".to_string(),
                "LAND".to_string(),
                "TECH3".to_string(),
            ],
        },
        // T1 Land Units
        Unit {
            unit_id: "UEL0101".to_string(),
            faction: Faction::Uef,
            name: Some("Snoop".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 12,
            build_cost_energy: 80,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0106".to_string(),
            faction: Faction::Uef,
            name: Some("Mech Marine".to_string()),
            description: "Light Assault Bot".to_string(),
            build_cost_mass: 30,
            build_cost_energy: 120,
            build_time: 120,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0103".to_string(),
            faction: Faction::Uef,
            name: Some("Lobo".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0201".to_string(),
            faction: Faction::Uef,
            name: Some("MA12 Striker".to_string()),
            description: "Medium Tank".to_string(),
            build_cost_mass: 56,
            build_cost_energy: 266,
            build_time: 300,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0104".to_string(),
            faction: Faction::Uef,
            name: Some("Archer".to_string()),
            description: "Mobile Anti-Air Gun".to_string(),
            build_cost_mass: 55,
            build_cost_energy: 275,
            build_time: 220,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "UEL0202".to_string(),
            faction: Faction::Uef,
            name: Some("Pillar".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 198,
            build_cost_energy: 990,
            build_time: 880,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0203".to_string(),
            faction: Faction::Uef,
            name: Some("Riptide".to_string()),
            description: "Amphibious Tank".to_string(),
            build_cost_mass: 320,
            build_cost_energy: 1650,
            build_time: 1420,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0307".to_string(),
            faction: Faction::Uef,
            name: Some("Parashield".to_string()),
            description: "Mobile Shield Generator".to_string(),
            build_cost_mass: 220,
            build_cost_energy: 900,
            build_time: 660,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "DEL0204".to_string(),
            faction: Faction::Uef,
            name: Some("Mongoose".to_string()),
            description: "Gatling Bot".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 1000,
            build_time: 1000,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0111".to_string(),
            faction: Faction::Uef,
            name: Some("Flapjack".to_string()),
            description: "Mobile Missile Launcher".to_string(),
            build_cost_mass: 180,
            build_cost_energy: 1350,
            build_time: 800,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0205".to_string(),
            faction: Faction::Uef,
            name: Some("Sky Boxer".to_string()),
            description: "Mobile AA Flak Artillery".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 800,
            build_time: 800,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XEL0209".to_string(),
            faction: Faction::Uef,
            name: Some("Sparky".to_string()),
            description: "Field Engineer".to_string(),
            build_cost_mass: 225,
            build_cost_energy: 1000,
            build_time: 1000,
            categories: vec![
                "ENGINEER".to_string(),
                "LAND".to_string(),
                "TECH2".to_string(),
            ],
        },
        // T3 Land Units
        Unit {
            unit_id: "UEL0303".to_string(),
            faction: Faction::Uef,
            name: Some("Titan".to_string()),
            description: "Heavy Assault Bot".to_string(),
            build_cost_mass: 480,
            build_cost_energy: 5250,
            build_time: 2400,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEL0304".to_string(),
            faction: Faction::Uef,
            name: Some("Demolisher".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XEL0305".to_string(),
            faction: Faction::Uef,
            name: Some("Percival".to_string()),
            description: "Armored Assault Bot".to_string(),
            build_cost_mass: 1280,
            build_cost_energy: 14000,
            build_time: 4800,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XEL0306".to_string(),
            faction: Faction::Uef,
            name: Some("Spearhead".to_string()),
            description: "Mobile Missile Platform".to_string(),
            build_cost_mass: 400,
            build_cost_energy: 3000,
            build_time: 2400,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "DELK002".to_string(),
            faction: Faction::Uef,
            name: Some("Cougar".to_string()),
            description: "Mobile Rapid-fire AA Cannon".to_string(),
            build_cost_mass: 600,
            build_cost_energy: 7500,
            build_time: 3000,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "UEB1101".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1102".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Hydrocarbon Power Plant".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 800,
            build_time: 400,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1103".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1104".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 4000,
            build_time: 500,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB1105".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Energy Storage".to_string(),
            build_cost_mass: 250,
            build_cost_energy: 1200,
            build_time: 200,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1106".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Storage".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 1500,
            build_time: 250,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "UEB1201".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB1202".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "UEB1301".to_string(),
            faction: Faction::Uef,
            name: Some("EG 900 Fusion Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB1302".to_string(),
            faction: Faction::Uef,
            name: Some("Mass Pump 3".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB1303".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // T1 Factories
        Unit {
            unit_id: "UEB0101".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Land Factory".to_string(),
            build_cost_mass: 240,
            build_cost_energy: 2100,
            build_time: 300,
            categories: vec![
                "STRUCTURE".to_string(),
                "TECH1".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0102".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory".to_string(),
            build_cost_mass: 210,
            build_cost_energy: 2400,
            build_time: 300,
            categories: vec![
                "STRUCTURE".to_string(),
                "TECH1".to_string(),
                "AIR".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0103".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory".to_string(),
            build_cost_mass: 300,
            build_cost_energy: 1500,
            build_time: 300,
            categories: vec![
                "STRUCTURE".to_string(),
                "TECH1".to_string(),
                "NAVAL".to_string(),
            ],
        },
        // T2 Factories
        Unit {
            unit_id: "UEB0201".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Land Factory HQ".to_string(),
            build_cost_mass: 1410,
            build_cost_energy: 11200,
            build_time: 2300,
            categories: vec![
                "LAND".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0202".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory HQ".to_string(),
            build_cost_mass: 920,
            build_cost_energy: 18000,
            build_time: 2300,
            categories: vec![
                "AIR".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0203".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory HQ".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 10000,
            build_time: 3200,
            categories: vec![
                "NAVAL".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9501".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Land Factory".to_string(),
            build_cost_mass: 580,
            build_cost_energy: 4800,
            build_time: 1200,
            categories: vec![
                "LAND".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9502".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory".to_string(),
            build_cost_mass: 510,
            build_cost_energy: 8000,
            build_time: 1200,
            categories: vec![
                "AIR".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9503".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory".to_string(),
            build_cost_mass: 1100,
            build_cost_energy: 5500,
            build_time: 2000,
            categories: vec![
                "NAVAL".to_string(),
                "STRUCTURE".to_string(),
                "TECH2".to_string(),
            ],
        },
        // T3 Factories
        Unit {
            unit_id: "UEB0301".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Land Factory HQ".to_string(),
            build_cost_mass: 5220,
            build_cost_energy: 47400,
            build_time: 12000,
            categories: vec![
                "LAND".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0302".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory HQ".to_string(),
            build_cost_mass: 4090,
            build_cost_energy: 99400,
            build_time: 12000,
            categories: vec![
                "AIR".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0303".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory HQ".to_string(),
            build_cost_mass: 9500,
            build_cost_energy: 45000,
            build_time: 21600,
            categories: vec![
                "NAVAL".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9601".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Suport Land Factory".to_string(),
            build_cost_mass: 1440,
            build_cost_energy: 11600,
            build_time: 3200,
            categories: vec![
                "LAND".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9602".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory".to_string(),
            build_cost_mass: 1510,
            build_cost_energy: 34000,
            build_time: 3200,
            categories: vec![
                "AIR".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "ZEB9603".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory".to_string(),
            build_cost_mass: 2200,
            build_cost_energy: 11000,
            build_time: 10800,
            categories: vec![
                "NAVAL".to_string(),
                "STRUCTURE".to_string(),
                "TECH3".to_string(),
            ],
        },
        Unit {
            unit_id: "UEB0304".to_string(),
            faction: Faction::Uef,
            name: Some("QGW R-32".to_string()),
            description: "Quantum Gateway".to_string(),
            build_cost_mass: 3000,
            build_cost_energy: 30000,
            build_time: 4097,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // T1 Defense
        Unit {
            unit_id: "UEB2101".to_string(),
            faction: Faction::Uef,
            name: Some("DM1 Plasma Cannon".to_string()),
            description: "Point Defense".to_string(),
            build_cost_mass: 250,
            build_cost_energy: 2000,
            build_time: 250,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB2104".to_string(),
            faction: Faction::Uef,
            name: Some("DA1 Railgun".to_string()),
            description: "Anti-Air Turret".to_string(),
            build_cost_mass: 150,
            build_cost_energy: 1500,
            build_time: 188,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB2109".to_string(),
            faction: Faction::Uef,
            name: Some("DN1".to_string()),
            description: "Torpedo Launcher".to_string(),
            build_cost_mass: 450,
            build_cost_energy: 3600,
            build_time: 450,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Defense
        Unit {
            unit_id: "UEB2204".to_string(),
            faction: Faction::Uef,
            name: Some("Air Cleaner".to_string()),
            description: "Anti-Air Flak Artillery".to_string(),
            build_cost_mass: 400,
            build_cost_energy: 4000,
            build_time: 540,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB2205".to_string(),
            faction: Faction::Uef,
            name: Some("Tsunami".to_string()),
            description: "Torpedo Launcher".to_string(),
            build_cost_mass: 1080,
            build_cost_energy: 9000,
            build_time: 1446,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB2301".to_string(),
            faction: Faction::Uef,
            name: Some("Triad".to_string()),
            description: "Point Defense".to_string(),
            build_cost_mass: 540,
            build_cost_energy: 3780,
            build_time: 675,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB2303".to_string(),
            faction: Faction::Uef,
            name: Some("Klink Hammer".to_string()),
            description: "Artillery Installation".to_string(),
            build_cost_mass: 1900,
            build_cost_energy: 13585,
            build_time: 1600,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB2108".to_string(),
            faction: Faction::Uef,
            name: Some("Aloha".to_string()),
            description: "Tactical Missile Launcher".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 4000,
            build_time: 800,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB4201".to_string(),
            faction: Faction::Uef,
            name: Some("Buzzkill".to_string()),
            description: "Tactical Missile Defense".to_string(),
            build_cost_mass: 280,
            build_cost_energy: 3200,
            build_time: 400,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB4202".to_string(),
            faction: Faction::Uef,
            name: Some("SD - Pulse".to_string()),
            description: "Shield Generator".to_string(),
            build_cost_mass: 600,
            build_cost_energy: 6000,
            build_time: 1150,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB4203".to_string(),
            faction: Faction::Uef,
            name: Some("Scattershield".to_string()),
            description: "Stealth Field Generator".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 5400,
            build_time: 664,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Defense
        Unit {
            unit_id: "UEB2302".to_string(),
            faction: Faction::Uef,
            name: Some("Duke".to_string()),
            description: "Heavy Artillery Installation".to_string(),
            build_cost_mass: 76000,
            build_cost_energy: 1424000,
            build_time: 121400,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB2304".to_string(),
            faction: Faction::Uef,
            name: Some("Flayer".to_string()),
            description: "Anti-Air SAM Launcher".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 1400,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB2305".to_string(),
            faction: Faction::Uef,
            name: Some("Stonager".to_string()),
            description: "Strategic Missile Launcher".to_string(),
            build_cost_mass: 16500,
            build_cost_energy: 412500,
            build_time: 25000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB4301".to_string(),
            faction: Faction::Uef,
            name: Some("HSD Pulse".to_string()),
            description: "Heavy Shield Generator".to_string(),
            build_cost_mass: 3300,
            build_cost_energy: 55000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB4302".to_string(),
            faction: Faction::Uef,
            name: Some("Nuke Eliminator".to_string()),
            description: "Strategic Missile Defense".to_string(),
            build_cost_mass: 7500,
            build_cost_energy: 105000,
            build_time: 5841,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XEB2306".to_string(),
            faction: Faction::Uef,
            name: Some("Ravager".to_string()),
            description: "Heavy Point Defense".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 17600,
            build_time: 2000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // T1 Intel
        Unit {
            unit_id: "UEB3101".to_string(),
            faction: Faction::Uef,
            name: Some("SA1 - 1000".to_string()),
            description: "Radar System".to_string(),
            build_cost_mass: 80,
            build_cost_energy: 720,
            build_time: 80,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB3102".to_string(),
            faction: Faction::Uef,
            name: Some("SP1 - 1000".to_string()),
            description: "Sonar System".to_string(),
            build_cost_mass: 150,
            build_cost_energy: 1250,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Intel
        Unit {
            unit_id: "UEB3201".to_string(),
            faction: Faction::Uef,
            name: Some("SA2 - 2000".to_string()),
            description: "Radar System".to_string(),
            build_cost_mass: 180,
            build_cost_energy: 3600,
            build_time: 780,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB3202".to_string(),
            faction: Faction::Uef,
            name: Some("SP2 - 2000".to_string()),
            description: "Sonar System".to_string(),
            build_cost_mass: 300,
            build_cost_energy: 7200,
            build_time: 780,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Intel
        Unit {
            unit_id: "UEB3104".to_string(),
            faction: Faction::Uef,
            name: Some("SA3 - Omni".to_string()),
            description: "Omni Sensor Array".to_string(),
            build_cost_mass: 2400,
            build_cost_energy: 30000,
            build_time: 2400,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // T1 Support
        Unit {
            unit_id: "UEB5101".to_string(),
            faction: Faction::Uef,
            name: Some("Calcicrete".to_string()),
            description: "Wall Section".to_string(),
            build_cost_mass: 3,
            build_cost_energy: 20,
            build_time: 15,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB5202".to_string(),
            faction: Faction::Uef,
            name: Some("Refuel & Repair".to_string()),
            description: "Air Staging Facility".to_string(),
            build_cost_mass: 175,
            build_cost_energy: 2100,
            build_time: 350,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Support
        Unit {
            unit_id: "XEB0104".to_string(),
            faction: Faction::Uef,
            name: Some("The Kennel".to_string()),
            description: "Engineering Station".to_string(),
            build_cost_mass: 525,
            build_cost_energy: 2625,
            build_time: 1000,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Support
        Unit {
            unit_id: "XEB0204".to_string(),
            faction: Faction::Uef,
            name: Some("The Kennel".to_string()),
            description: "Engineering Station".to_string(),
            build_cost_mass: 1050,
            build_cost_energy: 5250,
            build_time: 2000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // ACU
        Unit {
            unit_id: "UEL0001".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Armored Command Unit".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 5000000,
            build_time: 6000000,
            categories: vec!["ENGINEER".to_string(), "LAND".to_string()],
        },
        // T1 Air Units
        Unit {
            unit_id: "UEA0101".to_string(),
            faction: Faction::Uef,
            name: Some("Hummingbird".to_string()),
            description: "Air Scout".to_string(),
            build_cost_mass: 40,
            build_cost_energy: 580,
            build_time: 200,
            categories: vec!["AIR".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEA0102".to_string(),
            faction: Faction::Uef,
            name: Some("Cyclone".to_string()),
            description: "Interceptor".to_string(),
            build_cost_mass: 50,
            build_cost_energy: 2250,
            build_time: 500,
            categories: vec!["AIR".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEA0103".to_string(),
            faction: Faction::Uef,
            name: Some("Scorcher".to_string()),
            description: "Attack Bomber".to_string(),
            build_cost_mass: 90,
            build_cost_energy: 2050,
            build_time: 500,
            categories: vec!["AIR".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEA0107".to_string(),
            faction: Faction::Uef,
            name: Some("C-6 Courier".to_string()),
            description: "Light Air Transport".to_string(),
            build_cost_mass: 120,
            build_cost_energy: 4800,
            build_time: 800,
            categories: vec!["AIR".to_string(), "TECH1".to_string()],
        },
        // T2 Air Units
        Unit {
            unit_id: "UEA0104".to_string(),
            faction: Faction::Uef,
            name: Some("C14 Star Lifter".to_string()),
            description: "Air Transport".to_string(),
            build_cost_mass: 330,
            build_cost_energy: 13200,
            build_time: 2640,
            categories: vec!["AIR".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEA0203".to_string(),
            faction: Faction::Uef,
            name: Some("Stinger".to_string()),
            description: "Gunship".to_string(),
            build_cost_mass: 192,
            build_cost_energy: 3840,
            build_time: 1280,
            categories: vec!["AIR".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEA0204".to_string(),
            faction: Faction::Uef,
            name: Some("Stork".to_string()),
            description: "Torpedo Bomber".to_string(),
            build_cost_mass: 270,
            build_cost_energy: 8000,
            build_time: 1600,
            categories: vec!["AIR".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "DEA0202".to_string(),
            faction: Faction::Uef,
            name: Some("Janus".to_string()),
            description: "Fighter/Bomber".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 12600,
            build_time: 2800,
            categories: vec!["AIR".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XEA3204".to_string(),
            faction: Faction::Uef,
            name: Some("C-D2 \"Rover-2\"".to_string()),
            description: "Engineering Drone".to_string(),
            build_cost_mass: 100,
            build_cost_energy: 1000,
            build_time: 500,
            categories: vec![
                "AIR".to_string(),
                "ENGINEER".to_string(),
                "TECH2".to_string(),
            ],
        },
        // T3 Air Units
        Unit {
            unit_id: "UEA0302".to_string(),
            faction: Faction::Uef,
            name: Some("SR90 Blackbird".to_string()),
            description: "Spy Plane".to_string(),
            build_cost_mass: 195,
            build_cost_energy: 7500,
            build_time: 900,
            categories: vec!["AIR".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEA0303".to_string(),
            faction: Faction::Uef,
            name: Some("Wasp".to_string()),
            description: "Air Superiority Fighter".to_string(),
            build_cost_mass: 450,
            build_cost_energy: 51200,
            build_time: 3840,
            categories: vec!["AIR".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEA0304".to_string(),
            faction: Faction::Uef,
            name: Some("Ambassador".to_string()),
            description: "Strategic Bomber".to_string(),
            build_cost_mass: 1750,
            build_cost_energy: 180000,
            build_time: 12000,
            categories: vec!["AIR".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEA0305".to_string(),
            faction: Faction::Uef,
            name: Some("Broadsword".to_string()),
            description: "Heavy Gunship".to_string(),
            build_cost_mass: 1500,
            build_cost_energy: 65000,
            build_time: 6300,
            categories: vec!["AIR".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XEA0306".to_string(),
            faction: Faction::Uef,
            name: Some("Continental".to_string()),
            description: "Heavy Air Transport".to_string(),
            build_cost_mass: 1400,
            build_cost_energy: 52500,
            build_time: 5250,
            categories: vec!["AIR".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEA0003".to_string(),
            faction: Faction::Uef,
            name: Some("C-D3 \"Rover-3\"".to_string()),
            description: "Engineering Drone".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 1600,
            build_time: 400,
            categories: vec![
                "AIR".to_string(),
                "ENGINEER".to_string(),
                "TECH3".to_string(),
            ],
        },
        // T1 Naval Units
        Unit {
            unit_id: "UES0103".to_string(),
            faction: Faction::Uef,
            name: Some("Thunderhead Class".to_string()),
            description: "Frigate".to_string(),
            build_cost_mass: 280,
            build_cost_energy: 2800,
            build_time: 1400,
            categories: vec!["NAVAL".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UES0203".to_string(),
            faction: Faction::Uef,
            name: Some("Tigershark".to_string()),
            description: "Attack Submarine".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 2880,
            build_time: 1440,
            categories: vec!["NAVAL".to_string(), "TECH1".to_string()],
        },
        // T2 Naval Units
        Unit {
            unit_id: "UES0201".to_string(),
            faction: Faction::Uef,
            name: Some("Valiant Class".to_string()),
            description: "Destroyer".to_string(),
            build_cost_mass: 2250,
            build_cost_energy: 15000,
            build_time: 10000,
            categories: vec!["NAVAL".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UES0202".to_string(),
            faction: Faction::Uef,
            name: Some("Governor Class".to_string()),
            description: "Cruiser".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 18000,
            build_time: 8000,
            categories: vec!["NAVAL".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XES0102".to_string(),
            faction: Faction::Uef,
            name: Some("Cooper".to_string()),
            description: "Torpedo Boat".to_string(),
            build_cost_mass: 750,
            build_cost_energy: 6000,
            build_time: 3000,
            categories: vec!["NAVAL".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XES0205".to_string(),
            faction: Faction::Uef,
            name: Some("Bulwark".to_string()),
            description: "Shield Boat".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 9000,
            build_time: 3600,
            categories: vec!["NAVAL".to_string(), "TECH2".to_string()],
        },
        // T3 Naval Units
        Unit {
            unit_id: "UES0302".to_string(),
            faction: Faction::Uef,
            name: Some("Summit Class".to_string()),
            description: "Battleship".to_string(),
            build_cost_mass: 10000,
            build_cost_energy: 62000,
            build_time: 31600,
            categories: vec!["NAVAL".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UES0304".to_string(),
            faction: Faction::Uef,
            name: Some("Ace".to_string()),
            description: "Strategic Missile Submarine".to_string(),
            build_cost_mass: 9500,
            build_cost_energy: 152000,
            build_time: 20000,
            categories: vec!["NAVAL".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UES0305".to_string(),
            faction: Faction::Uef,
            name: Some("SP3 - 3000".to_string()),
            description: "Sonar Platform".to_string(),
            build_cost_mass: 1000,
            build_cost_energy: 12000,
            build_time: 1200,
            categories: vec!["NAVAL".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XES0307".to_string(),
            faction: Faction::Uef,
            name: Some("Neptune Class".to_string()),
            description: "Battlecruiser".to_string(),
            build_cost_mass: 7000,
            build_cost_energy: 60000,
            build_time: 25200,
            categories: vec!["NAVAL".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "UEL0401".to_string(),
            faction: Faction::Uef,
            name: Some("Fatboy".to_string()),
            description: "Experimental Mobile Factory".to_string(),
            build_cost_mass: 28000,
            build_cost_energy: 350000,
            build_time: 47500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
        Unit {
            unit_id: "UES0401".to_string(),
            faction: Faction::Uef,
            name: Some("Atlantis".to_string()),
            description: "Experimental Aircraft Carrier".to_string(),
            build_cost_mass: 12000,
            build_cost_energy: 150000,
            build_time: 20500,
            categories: vec!["EXPERIMENTAL".to_string(), "NAVAL".to_string()],
        },
        Unit {
            unit_id: "UEB2401".to_string(),
            faction: Faction::Uef,
            name: Some("Mavor".to_string()),
            description: "Experimental Artillery".to_string(),
            build_cost_mass: 224775,
            build_cost_energy: 5994000,
            build_time: 300000,
            categories: vec!["EXPERIMENTAL".to_string(), "STRUCTURE".to_string()],
        },
        Unit {
            unit_id: "XEB2402".to_string(),
            faction: Faction::Uef,
            name: Some("Novax Center".to_string()),
            description: "Experimental Satellite System".to_string(),
            build_cost_mass: 36000,
            build_cost_energy: 512000,
            build_time: 44800,
            categories: vec![
                "AIR".to_string(),
                "EXPERIMENTAL".to_string(),
                "STRUCTURE".to_string(),
            ],
        },
        Unit {
            unit_id: "XEA0002".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Defense Satellite".to_string(),
            build_cost_mass: 10000,
            build_cost_energy: 160000,
            build_time: 30000,
            categories: vec!["AIR".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Cybran units
pub fn cybran_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "URL0105".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH1".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "URL0208".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH2".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "URL0301".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 26400,
            build_time: 14400,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH3".to_string(),
                "LAND".to_string(),
            ],
        },
        // T1 Land Units
        Unit {
            unit_id: "URL0101".to_string(),
            faction: Faction::Cybran,
            name: Some("Mole".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 8,
            build_cost_energy: 60,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URL0107".to_string(),
            faction: Faction::Cybran,
            name: Some("Mantis".to_string()),
            description: "Assault Bot".to_string(),
            build_cost_mass: 56,
            build_cost_energy: 273,
            build_time: 285,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URL0103".to_string(),
            faction: Faction::Cybran,
            name: Some("Medusa".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "URL0202".to_string(),
            faction: Faction::Cybran,
            name: Some("Rhino".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 290,
            build_cost_energy: 1500,
            build_time: 1300,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URL0203".to_string(),
            faction: Faction::Cybran,
            name: Some("Wagner".to_string()),
            description: "Amphibious Tank".to_string(),
            build_cost_mass: 297,
            build_cost_energy: 1980,
            build_time: 1320,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URL0306".to_string(),
            faction: Faction::Cybran,
            name: Some("Deceiver".to_string()),
            description: "Mobile Stealth Field System".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 1600,
            build_time: 800,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "URL0303".to_string(),
            faction: Faction::Cybran,
            name: Some("Loyalist".to_string()),
            description: "Siege Assault Bot".to_string(),
            build_cost_mass: 480,
            build_cost_energy: 5250,
            build_time: 2400,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URL0304".to_string(),
            faction: Faction::Cybran,
            name: Some("Trebuchet".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "URB1101".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URB1103".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URB1104".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 4000,
            build_time: 500,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "URB1201".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URB1202".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "URB1301".to_string(),
            faction: Faction::Cybran,
            name: Some("Ion Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URB1302".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URB1303".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "URL0402".to_string(),
            faction: Faction::Cybran,
            name: Some("Monkeylord".to_string()),
            description: "Experimental Spiderbot".to_string(),
            build_cost_mass: 20000,
            build_cost_energy: 260000,
            build_time: 27500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
        Unit {
            unit_id: "URL0401".to_string(),
            faction: Faction::Cybran,
            name: Some("Scathis".to_string()),
            description: "Experimental Mobile Rapid-Fire Artillery".to_string(),
            build_cost_mass: 220000,
            build_cost_energy: 4000000,
            build_time: 240000,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Aeon units
pub fn aeon_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "UAL0105".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH1".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UAL0208".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH2".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "UAL0301".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 1950,
            build_cost_energy: 27100,
            build_time: 14400,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH3".to_string(),
                "LAND".to_string(),
            ],
        },
        // T1 Land Units
        Unit {
            unit_id: "UAL0101".to_string(),
            faction: Faction::Aeon,
            name: Some("Spirit".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 8,
            build_cost_energy: 60,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0106".to_string(),
            faction: Faction::Aeon,
            name: Some("Flare".to_string()),
            description: "Light Assault Bot".to_string(),
            build_cost_mass: 42,
            build_cost_energy: 165,
            build_time: 160,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0103".to_string(),
            faction: Faction::Aeon,
            name: Some("Fervor".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0201".to_string(),
            faction: Faction::Aeon,
            name: Some("Aurora".to_string()),
            description: "Light Tank".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 270,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "UAL0202".to_string(),
            faction: Faction::Aeon,
            name: Some("Obsidian".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 1800,
            build_time: 1600,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "UAL0303".to_string(),
            faction: Faction::Aeon,
            name: Some("Harbinger Mark IV".to_string()),
            description: "Heavy Assault Bot".to_string(),
            build_cost_mass: 840,
            build_cost_energy: 9600,
            build_time: 3600,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAL0304".to_string(),
            faction: Faction::Aeon,
            name: Some("Serenity".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "UAB1101".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAB1103".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "UAB1201".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UAB1202".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "UAB1301".to_string(),
            faction: Faction::Aeon,
            name: Some("Quantum Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAB1302".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAB1303".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "UAL0401".to_string(),
            faction: Faction::Aeon,
            name: Some("Galactic Colossus".to_string()),
            description: "Experimental Assault Bot".to_string(),
            build_cost_mass: 27500,
            build_cost_energy: 343750,
            build_time: 51500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Seraphim units
pub fn seraphim_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "XSL0105".to_string(),
            faction: Faction::Seraphim,
            name: Some("Iya-istle".to_string()),
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH1".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "XSL0208".to_string(),
            faction: Faction::Seraphim,
            name: Some("Iya".to_string()),
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH2".to_string(),
                "LAND".to_string(),
            ],
        },
        Unit {
            unit_id: "XSL0301".to_string(),
            faction: Faction::Seraphim,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2400,
            build_cost_energy: 30200,
            build_time: 14400,
            categories: vec![
                "ENGINEER".to_string(),
                "TECH3".to_string(),
                "LAND".to_string(),
            ],
        },
        // T1 Land Units
        Unit {
            unit_id: "XSL0101".to_string(),
            faction: Faction::Seraphim,
            name: Some("Selen".to_string()),
            description: "Combat Scout".to_string(),
            build_cost_mass: 20,
            build_cost_energy: 80,
            build_time: 90,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSL0103".to_string(),
            faction: Faction::Seraphim,
            name: Some("Zthuee".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 180,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSL0201".to_string(),
            faction: Faction::Seraphim,
            name: Some("Thaam".to_string()),
            description: "Medium Tank".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 270,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "XSL0202".to_string(),
            faction: Faction::Seraphim,
            name: Some("Ilshavoh".to_string()),
            description: "Assault Bot".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 1800,
            build_time: 1600,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "XSL0303".to_string(),
            faction: Faction::Seraphim,
            name: Some("Othuum".to_string()),
            description: "Siege Tank".to_string(),
            build_cost_mass: 840,
            build_cost_energy: 9600,
            build_time: 3600,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSL0304".to_string(),
            faction: Faction::Seraphim,
            name: Some("Suthanus".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "XSB1101".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSB1103".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "XSB1201".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XSB1202".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "XSB1301".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSB1302".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSB1303".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyaliya".to_string()),
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "XSL0401".to_string(),
            faction: Faction::Seraphim,
            name: Some("Ythotha".to_string()),
            description: "Experimental Assault Bot".to_string(),
            build_cost_mass: 26500,
            build_cost_energy: 330000,
            build_time: 46875,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}
