//! Hardcoded unit data for the eco guide
//! These units are embedded in the frontend for GitHub Pages deployment

use super::unit::{Faction, Unit};
use std::collections::HashMap;

/// Get the base engineer unit ID for each faction
pub fn faction_engineer_id(faction: Faction) -> &'static str {
    match faction {
        Faction::Uef => "UEL0105",
        Faction::Cybran => "URL0105",
        Faction::Aeon => "UAL0105",
        Faction::Seraphim => "XSL0105",
    }
}

/// Get all units as a vector
pub fn all_units() -> Vec<Unit> {
    let mut units = Vec::new();
    units.extend(uef_units());
    units.extend(cybran_units());
    units.extend(aeon_units());
    units.extend(seraphim_units());
    units
}

/// Get units grouped by faction
pub fn units_by_faction() -> HashMap<Faction, Vec<Unit>> {
    let mut map = HashMap::new();
    for faction in Faction::all() {
        let units: Vec<Unit> = all_units()
            .into_iter()
            .filter(|u| u.faction == faction)
            .collect();
        map.insert(faction, units);
    }
    map
}

/// Find a unit by its unit_id
pub fn find_unit(unit_id: &str) -> Option<Unit> {
    all_units().into_iter().find(|u| u.unit_id == unit_id)
}

/// UEF units
pub fn uef_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "UEL0105".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec!["ENGINEER".to_string(), "TECH1".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "UEL0208".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec!["ENGINEER".to_string(), "TECH2".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "UEL0301".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2100,
            build_cost_energy: 25200,
            build_time: 14400,
            categories: vec!["ENGINEER".to_string(), "TECH3".to_string(), "LAND".to_string()],
        },
        // T1 Land Units
        Unit {
            unit_id: "UEL0101".to_string(),
            faction: Faction::Uef,
            name: Some("Snoop".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 12,
            build_cost_energy: 80,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0106".to_string(),
            faction: Faction::Uef,
            name: Some("Mech Marine".to_string()),
            description: "Light Assault Bot".to_string(),
            build_cost_mass: 30,
            build_cost_energy: 120,
            build_time: 120,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0103".to_string(),
            faction: Faction::Uef,
            name: Some("Lobo".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEL0201".to_string(),
            faction: Faction::Uef,
            name: Some("MA12 Striker".to_string()),
            description: "Medium Tank".to_string(),
            build_cost_mass: 56,
            build_cost_energy: 266,
            build_time: 300,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "UEL0202".to_string(),
            faction: Faction::Uef,
            name: Some("Pillar".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 198,
            build_cost_energy: 990,
            build_time: 880,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0203".to_string(),
            faction: Faction::Uef,
            name: Some("Riptide".to_string()),
            description: "Amphibious Tank".to_string(),
            build_cost_mass: 320,
            build_cost_energy: 1650,
            build_time: 1420,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEL0307".to_string(),
            faction: Faction::Uef,
            name: Some("Parashield".to_string()),
            description: "Mobile Shield Generator".to_string(),
            build_cost_mass: 220,
            build_cost_energy: 900,
            build_time: 660,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "UEL0303".to_string(),
            faction: Faction::Uef,
            name: Some("Titan".to_string()),
            description: "Heavy Assault Bot".to_string(),
            build_cost_mass: 480,
            build_cost_energy: 5250,
            build_time: 2400,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEL0304".to_string(),
            faction: Faction::Uef,
            name: Some("Demolisher".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "UEB1101".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1102".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Hydrocarbon Power Plant".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 800,
            build_time: 400,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1103".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1104".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 4000,
            build_time: 500,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB1105".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Energy Storage".to_string(),
            build_cost_mass: 250,
            build_cost_energy: 1200,
            build_time: 200,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UEB1106".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Storage".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 1500,
            build_time: 250,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "UEB1201".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UEB1202".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "UEB1301".to_string(),
            faction: Faction::Uef,
            name: Some("EG 900 Fusion Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB1302".to_string(),
            faction: Faction::Uef,
            name: Some("Mass Pump 3".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UEB1303".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // T1 Factories
        Unit {
            unit_id: "UEB0101".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Land Factory".to_string(),
            build_cost_mass: 240,
            build_cost_energy: 2100,
            build_time: 300,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "UEB0102".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Air Factory".to_string(),
            build_cost_mass: 210,
            build_cost_energy: 2400,
            build_time: 300,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string(), "AIR".to_string()],
        },
        Unit {
            unit_id: "UEB0103".to_string(),
            faction: Faction::Uef,
            name: None,
            description: "Naval Factory".to_string(),
            build_cost_mass: 300,
            build_cost_energy: 1500,
            build_time: 300,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string(), "NAVAL".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "UEL0401".to_string(),
            faction: Faction::Uef,
            name: Some("Fatboy".to_string()),
            description: "Experimental Mobile Factory".to_string(),
            build_cost_mass: 28000,
            build_cost_energy: 350000,
            build_time: 47500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Cybran units
pub fn cybran_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "URL0105".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec!["ENGINEER".to_string(), "TECH1".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "URL0208".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec!["ENGINEER".to_string(), "TECH2".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "URL0301".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2000,
            build_cost_energy: 26400,
            build_time: 14400,
            categories: vec!["ENGINEER".to_string(), "TECH3".to_string(), "LAND".to_string()],
        },
        // T1 Land Units
        Unit {
            unit_id: "URL0101".to_string(),
            faction: Faction::Cybran,
            name: Some("Mole".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 8,
            build_cost_energy: 60,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URL0107".to_string(),
            faction: Faction::Cybran,
            name: Some("Mantis".to_string()),
            description: "Assault Bot".to_string(),
            build_cost_mass: 56,
            build_cost_energy: 273,
            build_time: 285,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URL0103".to_string(),
            faction: Faction::Cybran,
            name: Some("Medusa".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "URL0202".to_string(),
            faction: Faction::Cybran,
            name: Some("Rhino".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 290,
            build_cost_energy: 1500,
            build_time: 1300,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URL0203".to_string(),
            faction: Faction::Cybran,
            name: Some("Wagner".to_string()),
            description: "Amphibious Tank".to_string(),
            build_cost_mass: 297,
            build_cost_energy: 1980,
            build_time: 1320,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URL0306".to_string(),
            faction: Faction::Cybran,
            name: Some("Deceiver".to_string()),
            description: "Mobile Stealth Field System".to_string(),
            build_cost_mass: 160,
            build_cost_energy: 1600,
            build_time: 800,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "URL0303".to_string(),
            faction: Faction::Cybran,
            name: Some("Loyalist".to_string()),
            description: "Siege Assault Bot".to_string(),
            build_cost_mass: 480,
            build_cost_energy: 5250,
            build_time: 2400,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URL0304".to_string(),
            faction: Faction::Cybran,
            name: Some("Trebuchet".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "URB1101".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URB1103".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "URB1104".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 200,
            build_cost_energy: 4000,
            build_time: 500,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "URB1201".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "URB1202".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "URB1301".to_string(),
            faction: Faction::Cybran,
            name: Some("Ion Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URB1302".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "URB1303".to_string(),
            faction: Faction::Cybran,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "URL0402".to_string(),
            faction: Faction::Cybran,
            name: Some("Monkeylord".to_string()),
            description: "Experimental Spiderbot".to_string(),
            build_cost_mass: 20000,
            build_cost_energy: 260000,
            build_time: 27500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
        Unit {
            unit_id: "URL0401".to_string(),
            faction: Faction::Cybran,
            name: Some("Scathis".to_string()),
            description: "Experimental Mobile Rapid-Fire Artillery".to_string(),
            build_cost_mass: 220000,
            build_cost_energy: 4000000,
            build_time: 240000,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Aeon units
pub fn aeon_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "UAL0105".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec!["ENGINEER".to_string(), "TECH1".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "UAL0208".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec!["ENGINEER".to_string(), "TECH2".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "UAL0301".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 1950,
            build_cost_energy: 27100,
            build_time: 14400,
            categories: vec!["ENGINEER".to_string(), "TECH3".to_string(), "LAND".to_string()],
        },
        // T1 Land Units
        Unit {
            unit_id: "UAL0101".to_string(),
            faction: Faction::Aeon,
            name: Some("Spirit".to_string()),
            description: "Land Scout".to_string(),
            build_cost_mass: 8,
            build_cost_energy: 60,
            build_time: 60,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0106".to_string(),
            faction: Faction::Aeon,
            name: Some("Flare".to_string()),
            description: "Light Assault Bot".to_string(),
            build_cost_mass: 42,
            build_cost_energy: 165,
            build_time: 160,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0103".to_string(),
            faction: Faction::Aeon,
            name: Some("Fervor".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 180,
            build_time: 200,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAL0201".to_string(),
            faction: Faction::Aeon,
            name: Some("Aurora".to_string()),
            description: "Light Tank".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 270,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "UAL0202".to_string(),
            faction: Faction::Aeon,
            name: Some("Obsidian".to_string()),
            description: "Heavy Tank".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 1800,
            build_time: 1600,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "UAL0303".to_string(),
            faction: Faction::Aeon,
            name: Some("Harbinger Mark IV".to_string()),
            description: "Heavy Assault Bot".to_string(),
            build_cost_mass: 840,
            build_cost_energy: 9600,
            build_time: 3600,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAL0304".to_string(),
            faction: Faction::Aeon,
            name: Some("Serenity".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "UAB1101".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "UAB1103".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "UAB1201".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "UAB1202".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "UAB1301".to_string(),
            faction: Faction::Aeon,
            name: Some("Quantum Reactor".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAB1302".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "UAB1303".to_string(),
            faction: Faction::Aeon,
            name: None,
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "UAL0401".to_string(),
            faction: Faction::Aeon,
            name: Some("Galactic Colossus".to_string()),
            description: "Experimental Assault Bot".to_string(),
            build_cost_mass: 27500,
            build_cost_energy: 343750,
            build_time: 51500,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}

/// Seraphim units
pub fn seraphim_units() -> Vec<Unit> {
    vec![
        // Engineers
        Unit {
            unit_id: "XSL0105".to_string(),
            faction: Faction::Seraphim,
            name: Some("Iya-istle".to_string()),
            description: "Engineer".to_string(),
            build_cost_mass: 52,
            build_cost_energy: 260,
            build_time: 260,
            categories: vec!["ENGINEER".to_string(), "TECH1".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "XSL0208".to_string(),
            faction: Faction::Seraphim,
            name: Some("Iya".to_string()),
            description: "Engineer".to_string(),
            build_cost_mass: 130,
            build_cost_energy: 650,
            build_time: 650,
            categories: vec!["ENGINEER".to_string(), "TECH2".to_string(), "LAND".to_string()],
        },
        Unit {
            unit_id: "XSL0301".to_string(),
            faction: Faction::Seraphim,
            name: None,
            description: "Support Armored Command Unit".to_string(),
            build_cost_mass: 2400,
            build_cost_energy: 30200,
            build_time: 14400,
            categories: vec!["ENGINEER".to_string(), "TECH3".to_string(), "LAND".to_string()],
        },
        // T1 Land Units
        Unit {
            unit_id: "XSL0101".to_string(),
            faction: Faction::Seraphim,
            name: Some("Selen".to_string()),
            description: "Combat Scout".to_string(),
            build_cost_mass: 20,
            build_cost_energy: 80,
            build_time: 90,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSL0103".to_string(),
            faction: Faction::Seraphim,
            name: Some("Zthuee".to_string()),
            description: "Mobile Light Artillery".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 180,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSL0201".to_string(),
            faction: Faction::Seraphim,
            name: Some("Thaam".to_string()),
            description: "Medium Tank".to_string(),
            build_cost_mass: 54,
            build_cost_energy: 270,
            build_time: 290,
            categories: vec!["LAND".to_string(), "TECH1".to_string()],
        },
        // T2 Land Units
        Unit {
            unit_id: "XSL0202".to_string(),
            faction: Faction::Seraphim,
            name: Some("Ilshavoh".to_string()),
            description: "Assault Bot".to_string(),
            build_cost_mass: 360,
            build_cost_energy: 1800,
            build_time: 1600,
            categories: vec!["LAND".to_string(), "TECH2".to_string()],
        },
        // T3 Land Units
        Unit {
            unit_id: "XSL0303".to_string(),
            faction: Faction::Seraphim,
            name: Some("Othuum".to_string()),
            description: "Siege Tank".to_string(),
            build_cost_mass: 840,
            build_cost_energy: 9600,
            build_time: 3600,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSL0304".to_string(),
            faction: Faction::Seraphim,
            name: Some("Suthanus".to_string()),
            description: "Mobile Heavy Artillery".to_string(),
            build_cost_mass: 800,
            build_cost_energy: 8000,
            build_time: 4300,
            categories: vec!["LAND".to_string(), "TECH3".to_string()],
        },
        // T1 Economy Structures
        Unit {
            unit_id: "XSB1101".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 75,
            build_cost_energy: 750,
            build_time: 125,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        Unit {
            unit_id: "XSB1103".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 36,
            build_cost_energy: 360,
            build_time: 60,
            categories: vec!["STRUCTURE".to_string(), "TECH1".to_string()],
        },
        // T2 Economy Structures
        Unit {
            unit_id: "XSB1201".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 1200,
            build_cost_energy: 12000,
            build_time: 2198,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        Unit {
            unit_id: "XSB1202".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 900,
            build_cost_energy: 5400,
            build_time: 900,
            categories: vec!["STRUCTURE".to_string(), "TECH2".to_string()],
        },
        // T3 Economy Structures
        Unit {
            unit_id: "XSB1301".to_string(),
            faction: Faction::Seraphim,
            name: Some("Uya-iya".to_string()),
            description: "Power Generator".to_string(),
            build_cost_mass: 3240,
            build_cost_energy: 57600,
            build_time: 6824,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSB1302".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyalatoh".to_string()),
            description: "Mass Extractor".to_string(),
            build_cost_mass: 4600,
            build_cost_energy: 31625,
            build_time: 2875,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        Unit {
            unit_id: "XSB1303".to_string(),
            faction: Faction::Seraphim,
            name: Some("Hyaliya".to_string()),
            description: "Mass Fabricator".to_string(),
            build_cost_mass: 4000,
            build_cost_energy: 120000,
            build_time: 5000,
            categories: vec!["STRUCTURE".to_string(), "TECH3".to_string()],
        },
        // Experimentals
        Unit {
            unit_id: "XSL0401".to_string(),
            faction: Faction::Seraphim,
            name: Some("Ythotha".to_string()),
            description: "Experimental Assault Bot".to_string(),
            build_cost_mass: 26500,
            build_cost_energy: 330000,
            build_time: 46875,
            categories: vec!["LAND".to_string(), "EXPERIMENTAL".to_string()],
        },
    ]
}
